language: python
python:
  - "3.7"
  
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql 
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database covidtest;' -U postgres

script:
  - coverage run --source covid-app -m unittest discover tests

after_success:
  - coveralls