language: python

python:
  - "3.7"
  
install:
  - pip install -r requirements.txt	
  - pip install coverage
  - pip install coveralls

services:	
  - postgresql 	 

before_script:
  - psql -c 'create database covidtest;' -U postgres	

script:
  - coverage run --omit */site-packages/* -m unittest discover tests
  - coverage report

after_success:
  - coveralls 