language: python
python:
  - "3.7"
  
install:
  - pip install -r requirements.txt

services:
  - postgresql 
  
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database covidtest;' -U postgres

script:
  - "python -m unittest discover tests"

  