language: python
python:
  - "3.7"
  
install:
  - pip install -e . --use-mirrors

services:
  - postgresql 
  
before_script:
  - pip install -r requirements.txt --use-mirrors
  - psql -c 'create database covidtest;' -U postgres

script:
- -m unittest discover tests coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
